### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by xxorax** [clusterit/orca#2]
code.google.com/p/rsc is gone.
```
> go get -v -d code.google.com/p/rsc
package code.google.com/p/rsc: unable to detect version control system for code.google.com/ path
exit status 1
```
The new repo we need seems to be https://github.com/rsc/qr

They keep a clone of the Google Code repo : https://github.com/rsc/rsc .However, they moved from HG to GIT so the revision in the GLOCKFILE is wrong now.

**Comment by ulrichSchreiner** [comment]
hi

i'm sorry, but the project is completely inactive. it should not be too hard to move the dependencies to a tool like `dep` and update the revisions.
